"""initial_multitenant_schema

Revision ID: b2371fba953b
Revises: 
Create Date: 2026-05-19 22:05:01.068009
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = 'b2371fba953b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Ensure pgvector extension exists
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\"")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.Enum('starter', 'growth', 'pro', 'enterprise', name='tenantplan'), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'trial', 'cancelled', name='tenantstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_stripe_customer_id'), 'tenants', ['stripe_customer_id'], unique=False)
    op.create_table('api_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('ts', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_usage_tenant_id', 'api_usage', ['tenant_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icp_config', sa.JSON(), nullable=True),
    sa.Column('sequence', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_campaigns_tenant_id', 'campaigns', ['tenant_id'], unique=False)
    op.create_table('channel_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'linkedin', 'twitter', 'instagram', 'tiktok', name='channelenum'), nullable=False),
    sa.Column('status', sa.Enum('connected', 'disconnected', 'error', name='credentialstatus'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_channel_credentials_tenant_channel', 'channel_credentials', ['tenant_id', 'channel'], unique=True)
    op.create_index('ix_channel_credentials_tenant_id', 'channel_credentials', ['tenant_id'], unique=False)
    op.create_table('prospects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('twitter_handle', sa.String(length=100), nullable=True),
    sa.Column('instagram_handle', sa.String(length=100), nullable=True),
    sa.Column('tiktok_handle', sa.String(length=100), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prospects_tenant_id', 'prospects', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_tenant_email', 'users', ['tenant_id', 'email'], unique=True)
    op.create_index('ix_users_tenant_id', 'users', ['tenant_id'], unique=False)
    op.create_table('voice_examples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'linkedin', 'twitter', 'instagram', 'tiktok', name='channelenum'), nullable=False),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('final_text', sa.Text(), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_voice_examples_tenant_channel_refreshed', 'voice_examples', ['tenant_id', 'channel', 'refreshed_at'], unique=False)
    op.create_table('voice_profiles',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('founder_name', sa.String(length=255), nullable=False),
    sa.Column('tone', sa.String(length=100), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('taboo_phrases', sa.JSON(), nullable=True),
    sa.Column('target_outcome', sa.String(length=255), nullable=True),
    sa.Column('style_notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('prospect_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.Enum('email', 'linkedin', 'twitter', 'instagram', 'tiktok', name='channelenum'), nullable=False),
    sa.Column('status', sa.Enum('drafted', 'approved', 'sent', 'failed', 'replied', 'skipped', name='messagestatus'), nullable=False),
    sa.Column('draft_text', sa.Text(), nullable=True),
    sa.Column('final_text', sa.Text(), nullable=True),
    sa.Column('edit_count', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('reply_received_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_tenant_id', 'messages', ['tenant_id'], unique=False)
    op.create_index('ix_messages_tenant_status', 'messages', ['tenant_id', 'status'], unique=False)
    op.create_table('edits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('before', sa.Text(), nullable=False),
    sa.Column('after', sa.Text(), nullable=False),
    sa.Column('edit_type', sa.String(length=50), nullable=True),
    sa.Column('ts', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_edits_tenant_id', 'edits', ['tenant_id'], unique=False)
    op.create_table('replies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('classified_intent', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_replies_tenant_id', 'replies', ['tenant_id'], unique=False)
    op.create_table('voice_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_voice_embeddings_tenant_id', 'voice_embeddings', ['tenant_id'], unique=False)
    # ivfflat index for pgvector similarity search (requires vector extension)
    op.execute("CREATE INDEX IF NOT EXISTS ix_voice_embeddings_ivfflat ON voice_embeddings USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_voice_embeddings_tenant_id', table_name='voice_embeddings')
    op.drop_table('voice_embeddings')
    op.drop_index('ix_replies_tenant_id', table_name='replies')
    op.drop_table('replies')
    op.drop_index('ix_edits_tenant_id', table_name='edits')
    op.drop_table('edits')
    op.drop_index('ix_messages_tenant_status', table_name='messages')
    op.drop_index('ix_messages_tenant_id', table_name='messages')
    op.drop_table('messages')
    op.drop_table('voice_profiles')
    op.drop_index('ix_voice_examples_tenant_channel_refreshed', table_name='voice_examples')
    op.drop_table('voice_examples')
    op.drop_index('ix_users_tenant_id', table_name='users')
    op.drop_index('ix_users_tenant_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_prospects_tenant_id', table_name='prospects')
    op.drop_table('prospects')
    op.drop_index('ix_channel_credentials_tenant_id', table_name='channel_credentials')
    op.drop_index('ix_channel_credentials_tenant_channel', table_name='channel_credentials')
    op.drop_table('channel_credentials')
    op.drop_index('ix_campaigns_tenant_id', table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index('ix_api_usage_tenant_id', table_name='api_usage')
    op.drop_table('api_usage')
    op.drop_index(op.f('ix_tenants_stripe_customer_id'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
